name: rich_field_example
description: A demo app showcasing the rich_field_controller package in action.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  rich_field_controller:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
          style: normal
    - family: Codicons
      fonts:
        - asset: fonts/Codicons.ttf
