name: rich_field_controller
description: A rich text field controller that turn any Flutter TextField into
  an WYSIWYG editor.
version: 0.2.1
repository: 'https://github.com/yaitmou/rich_field_controller.git'
homepage: 'https://github.com/yaitmou/rich_field_controller.git'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  collection:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
