name: rich_field_controller
description: A rich text field controller to be used with Flutter TextField.
version: 0.1.1
repository: "https://github.com/yaitmou/rich_field_controller.git"
homepage: "https://github.com/yaitmou/rich_field_controller.git"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
