name: rich_field_controller
description: A rich text field controller that turn any Flutter TextField into
  an WYSIWYG editor.
version: 0.3.0
repository: 'https://github.com/yaitmou/rich_field_controller.git'
homepage: 'https://github.com/yaitmou/rich_field_controller.git'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  collection: null
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  replay_bloc: ^0.2.7

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
