name: rich_field_controller
description: A rich text field controller that turn any Flutter TextField into
  an WYSIWYG editor.
version: 0.3.0
repository: 'https://github.com/yaitmou/rich_field_controller.git'
homepage: 'https://github.com/yaitmou/rich_field_controller.git'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  collection: null
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  replay_bloc: ^0.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
